# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
<<<<<<< HEAD
  jaffle_shop:
    # Applies to all files under models/example/
    example:
      +materialized: table
=======
  kestis_projekt:
    +materialized: view  # Default for all models in the project
    raw:
      +materialized: view  # Materialization for models in the "raw" subfolder
>>>>>>> 93081079a2e479d39318ec8e51b01b8a74fd3577
